# Generated by Django 4.2.30 on 2026-07-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("title", models.CharField(max_length=200)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "category",
                    models.CharField(default="Other", max_length=100),
                ),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]